### ISSUE TITLE
DBD::SQLite::db prepare failed: no such table: message

### ISSUE THREAD

**Issue by MarkusLund** [chelseybaker/iOSMessageExport#10]
iOS 8.1.3
OSX 10.10.2

I get the following error message:

DBD::SQLite::db prepare failed: no such table: message at iOSMessageExport/iOSMessages.pm line 86.
DBD::SQLite::db prepare failed: no such table: message at iOSMessageExport/iOSMessages.pm line 86.

the _export folder is created with a style.css file. And a file which is called the same as my backup folder. But nothing more. 

My guess is that the table "message" is called something else in iOS 8.

**Comment by pooranis** [comment]
Try adding a forward slash to the end of the directory path:
`iOSMessageExport/backup.pl --directory_path backupdirectory/`
