### ISSUE TITLE
"Please make sure you have the correct access rights and the repository exists" Error

### ISSUE THREAD

**Issue by dominikaaaa** [chelseybaker/iOSMessageExport#15]
I am getting two errors: **one:** **Please make sure you have the correct access rights**
and the repository exists and **two:** **Can't open perl script "iOSMessageExport/backup.pl": No such file or directory
MacBook-Pro:iOSBackup dominika$ perl iOSMessageExport/backup.pl --directory_path 56e77e6902b0f8ebc80a7afe8992fddbf4dc8567/
Can't open perl script "iOSMessageExport/backup.pl": No such file or directory**

**Comment by zjacobson** [comment]
Did you try `git clone https://github.com/chelseybaker/iOSMessageExport.git` instead of ssh?  That may clear up error number one.   Error number two is likely because you never cloned the repository so there is no backup.pl file .
