### ISSUE TITLE
Can't locate DBI.pm Error

### ISSUE THREAD

**Issue by afield1235** [chelseybaker/iOSMessageExport#22]
OSX 10.13.2

This issue may be unique to my machine, maybe something I did but maybe someone can help.

Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /opt/local/lib/perl5/site_perl/5.24/darwin-thread-multi-2level /opt/local/lib/perl5/site_perl/5.24 /opt/local/lib/perl5/vendor_perl/5.24/darwin-thread-multi-2level /opt/local/lib/perl5/vendor_perl/5.24 /opt/local/lib/perl5/5.24/darwin-thread-multi-2level /opt/local/lib/perl5/5.24 .) at iOSSMSBackup.pm line 3.
BEGIN failed--compilation aborted at iOSSMSBackup.pm line 3.
Compilation failed in require at backup.pl line 7.
BEGIN failed--compilation aborted at backup.pl line 7.

**Comment by martinchapman** [comment]
`cpan`, the Perl package manager, should help with this, and I believe ships with OSX:

`cpan install DBI`.

Note that you may then encounter issue #20. Following the instructions there, to switch to this [fork](https://github.com/basnijholt/iOSMessageExport/commit/844242161cedfe5cd6172d0435cf86f91900a927), enabled me to export all messages from a recent backup.
