### ISSUE TITLE
Getting current date/time as timestamp for all messages

### ISSUE THREAD

**Issue by nbornstein** [chelseybaker/iOSMessageExport#23]
When I run the script all the messages a stamped with the date and time that I ran the script, not the date and time that the message was sent. 

I thought maybe it had something to do with the select statements in iOSMessages.pm, for example:
`WHEN date > 0 then TIME(date + 978307200, 'unixepoch', 'localtime')`
Maybe it should be this:
`WHEN m.date > 0 then TIME(m.date + 978307200, 'unixepoch', 'localtime')`

But that does not seem to change anything.

Any thoughts?

**Comment by mikeas-id** [comment]
use date/1000000000 (that's 9 zeros) in the sql statement.  Worked for me, gave me real dates and times rather than same random value for all.  Per @ron-fr comment error #19

**Comment by nbornstein** [comment]
Yeah, that fixes it. Thanks!
